title: "My Networking Blog"
author: "Ishan Sawhney"
description: "Routing, Switching Protocol Guides & Troubleshooting Notes"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-tagging
  - jekyll-pygments
paginate: 5
taggable: true
tags_path: /tags/
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
